#!/bin/sh
set -e

readonly CONFIG="${SSG_CONFIG:-.ssg}"
readonly ROOT_TITLE="${SSG_ROOT_TITLE}"
readonly TITLE_FORMAT="${SSG_TITLE_FORMAT-capitalize}"

println() {
    printf '%s\n' "$1"
}

is_function() {
    [ "$1" ] && [ "$(command -v "$1")" = "$1" ]
}

try() {
    if is_function "$1"; then "$1"; else false; fi
}

find_files() {
    find "$1" -name '.?*' -prune -o -type f -name "$2" -print
}

capitalize() {
    tr ' ' '\n' |
    while IFS='' read -r word; do
        printf ' %.1s' "$word" | tr '[:lower:]' '[:upper:]'
        printf '%s' "${word#?}"
    done | cut -c 2-
}

format_title() {
    if [ "${1%.*}" = "$1" ]; then
        println "$1" | tr '_-' '  ' | ${TITLE_FORMAT:-cat}
    else
        println "$1"
    fi
}

get_basename_title() {
    path="${1%/}"
    basename="${path##*/}"
    if [ "$basename" = "." ]; then
        if [ "$ROOT_TITLE" ]; then
            println "$ROOT_TITLE"
        else
            format_title "$(basename "$(pwd)")"
        fi
    else
        format_title "$basename"
    fi
}

get_filename_title() {
    path="${1%.*}"
    if [ "${path##*/}" = "index" ]; then
        get_basename_title "${path%/*}"
    else
        get_basename_title "$path"
    fi
}

input() {
    cat "${SOURCE_PATH:?}"
}

instantiate() {
    : "${GENERATOR:?}" "${TARGET:?}" "${TITLE:?}" "${DEST_PATH:?}"
    template_path="${1:+"$CONFIG/templates/$TARGET/$1.$TARGET"}"
    cat "${template_path:--}" |
        eval "printf '%s\\n' \"$(sed 's/"/\\"/g;s/`/\\`/g')\""
}

generate() {
    TITLE="$(try "get_${SOURCE_PATH##*.}_title" ||
        get_filename_title "$DEST_PATH")"
    cat "$CONFIG/templates/$TARGET/header.$TARGET" \
        "$CONFIG/templates/$TARGET/${SOURCE_PATH##*.}.main.$TARGET" \
        "$CONFIG/templates/$TARGET/footer.$TARGET" |
        instantiate | { try "${TARGET}_transform" || cat; }
}

import() {
    if [ -d "$1" ]; then
        for plugin in "$1"/*.sh; do
            if [ -e "$plugin" ]; then
                . "$plugin"
            fi
        done
    fi
}

run_generator() {
    unset SOURCE_PATH DEST_PATH TITLE
    TARGET="${1:?}"
    GENERATOR="${2:?}"
    "$2"
}

main() {
    import "$CONFIG/plugins"
    import "$CONFIG/hooks"
    GENERATOR="core"
    for templates in "$CONFIG/templates"/*; do
        TARGET="${templates##*/}"
        ls "$templates" | grep -F ".main.$TARGET" | sort |
        while IFS='' read -r template_filename; do
            find_files "." "*.${template_filename%%.*}" |
            while IFS='' read -r SOURCE_PATH; do
                DEST_PATH="${SOURCE_PATH%.*}.$TARGET"
                println "${DEST_PATH#./}" >&2
                generate > "$DEST_PATH"
            done
        done
    done
    try post_hook || true
}

cd "${1:-.}" || exit 1
main
