#!/bin/sh

EXT="${SSG_EXTENSION:-md}"
TITLE="${SSG_TITLE:-Home}"
PROCESSOR="${SSG_PROCESSOR:-smu}"
INCLUDES="${SSG_INCLUDES:-includes}"
CR="$(printf '\r')"

get_subdirs() {
    find "$1" ! -name "${1##*/}" -prune ! -name '.*' -type d
}

get_recursive_subdirs() {
    find "$1" -name ".?*" -prune -o -type d -print
}

has_subpage() {
    get_subdirs "$1" | {
        while IFS='' read -r subdir; do
            if [ -r "$subdir/index.html" ]; then
                return 0
            fi
        done
        return 1
    }
}

is_dir() {
    [ -d "$1" ] && [ ! -L "$1" ] && [ "${1##*/}" != "$INCLUDES" ]
}

is_content_page() {
    is_dir "$1" && ! has_subpage "$1" &&
        [ -r "$1/index.$EXT" -o -r "$1/index.html" ]
}

is_category_page() {
    is_dir "$1" && has_subpage "$1"
}

titlecase() {
    printf '%s\n' "$1" | tr '_ -' '\n\n\n' |
    while IFS='' read -r word; do
        printf ' %.1s' "$word" | tr '[:lower:]' '[:upper:]'
        printf "${word#?}"
    done | cut -c 2-
}

get_title() {
    titledir="${1%/}"
    if [ -r "$titledir/index.$EXT" ]; then
        head -n 1 "$titledir/index.$EXT"
    elif [ -r "$titledir/index.html" ]; then
        cat "$titledir/index.html" | tr -d '\r\n' |
            sed -n 's/<title>\(.*\)<\/title>/\1/p'
    elif [ "$titledir" == '.' ]; then
        printf "$TITLE"
    else
        titlecase "${titledir##*/}"
    fi
}

get_header() {
    if [ -r "$INCLUDES/header.html" ]; then
        cat "$INCLUDES/header.html"
    else
        printf '<!DOCTYPE html>\n<html lang="en">\n<head>\n'
        printf '<meta charset="utf-8">\n'
        printf '<meta name="created" content="">\n'
        printf '<meta name="modified" content="">\n'
        printf '<meta name="author" content="">\n'
        printf '<title></title>\n'
        printf '<link rel="stylesheet" href="/style.css">\n'
        printf '<link rel="icon" type="image/png" '
        printf 'href="data:image/png;base64,iVBORw0KGgo=">\n'
        printf '</head>\n<body>\n'
    fi
}

set_meta_tags() {
    source="$1"
    command=""
    while read -r line; do
        trimmed="${line#% }"
        if [ "$trimmed" == "$line" ]; then
            continue
        fi
        key="${trimmed%%:*}"
        value="${trimmed#*: }"
        command+="s|<meta name=\"$key\" content=\"\">|<meta name=\"$key\" content=\"$value\">|;"
    done < "$source"
    sed "${command%;}"
}

set_title() {
    sed "s|<title></title>|<title>$1</title>|"
}

get_footer() {
    if [ -r "$INCLUDES/footer.html" ]; then
        cat "$INCLUDES/footer.html"
    else
        printf "</body>\n</html>\n"
    fi
}

get_metadata() {
    key="$1"
    dir="$2"
    if [ -r "$dir/index.$EXT" ]; then
        sed -n "s/^% $key: \(.*\)$/\1/p" "$dir/index.$EXT"
    elif [ -r "$dir/index.html" ]; then
        sed -n "s/<dt>$key<\/dt><dd>\(.*\)<\/dd>/\1/p" "$dir/index.html"
    fi
}

gen_nav() {
    tail="${1%/}"
    if [ "$tail" == "." ]; then
        printf '<h6>\n</h6>\n'
        return
    fi
    tail="${tail%/*}/" # start with parent directory
    tail="${tail#.}"
    tail="${tail#/}"   #  a/b/    b/      ''
    head="/"           # /     /a/   /a/b/
    printf "<h6>\n"
    printf "<a href=\"$head\">$TITLE</a> &gt;\n"
    while [ "$tail" ]; do
        head="$head${tail%%/*}/"
        tail="${tail#*/}"
        label="$(get_title ".$head")"
        printf "<a href=\"$head\">$label</a> &gt;\n"
    done
    printf "</h6>\n"
}

gen_submenu() {
    dir="$1"
    printf "<h6>\n"
    get_subdirs "$dir" |
    while IFS='' read -r path; do
        if is_category_page "$path"; then
            title="$(get_title "$path")"
            printf "<a href=\"${path##*/}\">$title</a>\n"
        fi
    done
    printf "</h6>\n"
}

gen_listing() {
    dir="$1"
    (cd "$dir"; get_recursive_subdirs .) |
    while IFS='' read -r relpath; do
        path="${dir%/}/${relpath#./}"
        if is_content_page "$path"; then
            published="$(get_metadata Published "$path")"
            if [ "$published" ]; then
                printf "%s %s\n" "$published" "$relpath"
            fi
        fi
    done |
    sort -r -k 1 |
    while IFS='' read -r line; do
        published="${line%% *}"
        relpath="${line#* }"
        path="${dir%/}/${relpath#./}"
        title="$(get_title "$path")"
        printf "<h2><sup>$published</sup>"
        printf "<a href=\"${relpath#./}\">$title</a></h2>\n"
    done
}

gen_category_page() {
    dir="$1"
    html="$dir/index.html"
    title="$(get_title "$dir")"
    get_header | set_title "$title" > "$html"
    gen_nav "$dir" >> "$html"
    printf "<h1>%s</h1>\n" "$title" >> "$html"
    gen_submenu "$dir" >> "$html"
    gen_listing "$dir" >> "$html"
    get_footer >> "$html"
}

process() {
    cat "$1" | tr -d '\r' |
    sed "s/^% \([^:]*\): \(.*\)$/<dl>$CR<dt>\1<\/dt><dd>\2<\/dd>$CR<\/dl>/" |
        tr '\n' '\r' | sed "s/$CR<\/dl>$CR<dl>$CR/$CR/" | tr '\r' '\n' |
        $PROCESSOR | sed 's/^<p><dl>$/<dl>/' | sed 's/^<\/dl><\/p>$/<\/dl>/'
}

gen_content_page() {
    source="$1"
    html="${source%.*}.html"
    get_header | set_meta_tags "$source" |
        set_title "$(head -n 1 "$source")" > "$html"
    gen_nav "${source%/*}" >> "$html"
    process "$source" >> "$html"
    get_footer >> "$html"
}

gen_page() {
    dir="$1"
    for path in "$dir"/*."$EXT"; do
        if [ -r "$path" ]; then
            gen_content_page "$path"
        fi
    done
    if [ ! -e "$dir/index.html" ]; then
        if is_category_page "$dir"; then
            gen_category_page "$dir"
        fi
    fi
}

gen_site() {
    root="$1"
    get_recursive_subdirs "$root" |
    LC_ALL=C sort -r |
    while IFS='' read -r dir; do
        gen_page "$dir"
    done
}

gen_site "."
