#!/bin/sh
set -e

ROOT_TITLE="${SSG_ROOT_TITLE}"
TITLE_FORMAT="${SSG_TITLE_FORMAT-capitalize}"
CONFIG="${SSG_CONFIG:-.ssg}"

println() {
    printf '%s\n' "$1"
}

find_files() {
    find "$1" -name '.?*' -prune -o -type f -name "$2" -print
}

capitalize() {
    tr ' ' '\n' |
    while IFS='' read -r word; do
        printf ' %.1s' "$word" | tr '[:lower:]' '[:upper:]'
        printf '%s' "${word#?}"
    done | cut -c 2-
}

format_title() {
    if [ "${1%.*}" == "$1" ]; then
        println "$1" | tr '_-' '  ' | "${TITLE_FORMAT:-cat}"
    else
        println "$1"
    fi
}

get_basename_title() {
    path="${1%/}"
    basename="${path##*/}"
    if [ "$basename" == "." ]; then
        if [ "$ROOT_TITLE" ]; then
            println "$ROOT_TITLE"
        else
            format_title "$(basename "$(pwd)")"
        fi
    else
        format_title "$basename"
    fi
}

get_filename_title() {
    path="${1%.*}"
    if [ "${path##*/}" == "index" ]; then
        get_basename_title "${path%/*}"
    else
        get_basename_title "$path"
    fi
}

process_template() {
    eval "printf '%s\\n' \"$(sed 's/"/\\"/g')\""
}

get_header() {
    cat "$CONFIG/$target/templates/header.$target" | process_template
}

get_footer() {
    cat "$CONFIG/$target/templates/footer.$target" | process_template
}

read_source() {
    cat "$source_path"
}

register_generator() {
    GENERATORS="$GENERATORS$1;"
}

register_transform() {
    TRANSFORMS="$TRANSFORMS$1;"
}

apply_transforms() {
    if [ ! "$1" ]; then
        cat
    else
        "${1%%;*}" "$source_path" | apply_transforms "${1#*;}"
    fi
}

generate() {
    title="$(get_filename_title "$source_path")"
    cat "$CONFIG/$target/templates/header.$target" \
        "$CONFIG/$target/templates/${source_path##*.}.$target" \
        "$CONFIG/$target/templates/footer.$target" |
        process_template | apply_transforms "$TRANSFORMS"
}

import_plugins() {
    if [ -r "$1" ]; then
        for plugin in "$1"/*.sh; do
            if [ -r "$plugin" ]; then
                . "$plugin"
            fi
        done
    fi
}

main() {
    for target_config in "$CONFIG"/*; do
        target="${target_config##*/}"
        TRANSFORMS=""
        GENERATORS=""
        import_plugins "$target_config/plugins"
        ls "$target_config/templates" |
        grep -v -x -F -e "header.$target" -e "footer.$target" |
        while IFS='' read -r template_filename; do
            find_files "." "*.${template_filename%%.*}" |
            while IFS='' read -r source_path; do
                dest_path="${source_path%.*}.$target"
                println "${dest_path#./}" >&2
                generate > "$dest_path"
            done
        done
        eval "$GENERATORS"
    done
}

cd "${1:-.}" || exit 1
main
