# clean_html deletes all html files generated by stp

clean_html() {

_get_html_generator() {
    sed -n 's|<meta name="generator" content="\(.*\)">|\1|p' "$1" | head -n 1
}

_clean_html() {
    find_files "${1:-.}" "*.html" |
    while IFS='' read -r path; do
        generator="$(_get_html_generator "$path")"
        if [ "${generator#stp:}" != "$generator" ]; then
            rm "$path"
        fi
    done
}

_clean_html "$@"

}
